version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install -g http-server  # Simple server for static files
      - run: echo "Deploying static site"
      - persist_to_workspace:
          root: .
          paths: .
  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - attach_workspace:
          at: .
      - run: http-server -p 8080  # Hosts your app (adjust port if needed)

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires: [build]