version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build project
          command: npm run build

  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install Netlify CLI
          command: npm install -g netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --prod

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
