version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install -g http-server
      - run:
          name: Build static site
          command: |
            echo "Building static site"
            mkdir -p dist && cp -r * dist/
      - persist_to_workspace:
          root: dist
          paths: .

  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: Install Netlify CLI
          command: npm install -g netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --prod --dir dist

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires: [build]